### ISSUE TITLE
o site não carrega o textão

### ISSUE THREAD

**Issue by lamenezes** [joselitojunior1/ypsum#2]
o request http retorna o texto corretamente, mas a página não é atualizada fazendo com que só apareça a mensagem "Aguarde, estamos carregando seu textão."

isso no firefox 44.0.2 do ubuntu 15.10

**Comment by breakzplatform** [comment]
@lamenezes, algum output no console? No FF Developer Edition aqui eu não consigo reproduzir o erro

**Comment by lamenezes** [comment]
nenhum output no console... 
a variável textaoContent.innerText tem o textão, mas a página não atualiza. doido.

**Comment by lamenezes** [comment]
http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox
o firefox não dava suporte ao innerText desse jeito. alguma versão acima da minha funciona ou funcionará.

**Comment by breakzplatform** [comment]
[Funciona a partir do Firefox 45](https://bugzilla.mozilla.org/show_bug.cgi?id=264412). Não creio que valha a pena fazer uma verificação de browser para alterar o gerador, já que funciona em grande parte dos casos e tende a funcionar em todos a um curto prazo, então vou fechar a issue.

valeu @lamenezes
