### ISSUE TITLE
Subtítulo

### ISSUE THREAD

**Issue by skvggor** [joselitojunior1/ypsum#3]
Oi, achei engraçado a ideia :clap:. Parabéns.

No subtítulo, atualmente consta o texto:

```
O Lorem Ipsum que a Geração Y pensa precisa mas talvez ache que não.
```

E não deveria ser?

```
O Lorem Ipsum que a Geração Y pensa que precisa, mas talvez ache que não.
```

Espero ter ajudado.

Abraço.

**Comment by breakzplatform** [comment]
bem notado, @marcker. fiz rápido e nem notei. você quer mandar um PR com isso?

**Comment by skvggor** [comment]
@joselitojunior1, PR in progress.

**Comment by fguisso** [comment]
Aproveitar essa issue para dar os parabéns, mt bem pensado e engraçado, vou usar :D
